/* Tables Reference */
$tables = array("fl_accessi", //0
				"cms_articoli", //1
				"fl_gruppi",//2
				"messaggeria",//3
				"fl_info_servizi",//4
				"fl_cat_citta",//5
				"fl_eventi",//6
				"fl_links",//7
				"fl_admin",//8
				"fl_users",//9
				"cms_cat",//10
				"cms_sez",//11
				"cms_tipo",//12
				"cms_riepilogo",//13
				"cms_template",//14		
				"fl_accessi",//15
				"fl_cat_eventi",//16
				"fl_cat_province",//17	
				"fl_files",//18	
				"fl_cat_news",//19
				"cms_tematiche",//20
				"fl_conto",//21
				"fl_pagamenti_case",//22
				"sport_giornate",//23
				"sport_partite",//24
				"sport_societa",//25
				"fl_conferme",//26
				"fl_corrispettivi",//27
				"fl_cassa",//28
				"fl_posta",//29
				"fl_contenuti",//30
				"fl_palinesto",//31
				"fl_forum",//32
				"fl_messaggi",//33
				"fl_manutenzioni",//34
				"fl_attivita",//35
				"fl_contatti",//36
				"fl_banca",//37
				"fl_assistenza",//38
				"fl_profili",//39
				"fl_news",//40
				"fl_attivazioni",//41
				"fl_fax",///42
				"fl_pagamenti",//43
				"fl_segnalazioni",//44
				"fl_action_recorder",//45
				"fl_point_settimane",//46
				"fl_mobilmat",//47
				"fl_anagrafica",//48
				"fl_items",//49
				"fl_clienti",//50
				"fl_dem",//51
				"fl_liste_mail",//52
				"fl_mail",//53
				"fl_queries",//54
				"fl_codici",//55
				"fl_restaurants",//56
				"fl_potentials",//57
				"fl_vacancies",//58
				"fl_customers",//59
				"fl_meeting_agenda",//60
				"fl_interview_agenda",//61
				"fl_work_exp",//62
				"fl_studies",//63
				"fl_products_list",//64
				"fl_covers",//65
				"fl_sms",//66
				"fl_access_list",//67
				"fl_accounts",//68
				"fl_requests",//69
				"fl_articles",//70
				"fl_ricevute",//71
				"fl_training",//72
				"fl_customers_cv",//73
				"fl_corsi",//74
				"fl_lezioni",//75
				"fl_ricevute_ristoranti",//76
				"fl_subscriptions"//77
				);
				